services:
  lajemacartsapi:
    image: lajemacartsapi
    build:
      context: .
      dockerfile: LajemacartsApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_CONNECTION_STRING=Host=db;Port=5432;Database=lajemacarts_db;Username=user;Password=password
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: lajemacarts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: