// <auto-generated />
using System;
using GalleryContext.SecondaryAdapters.Repositories.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GalleryContext.SecondaryAdapters.Migrations
{
    [DbContext(typeof(ArtworkDbContext))]
    [Migration("20250711102340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("artwork_context")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalleryContext.SecondaryAdapters.Repositories.EntityFramework.Entities.ArtworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArtworkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("artwork_type_id");

                    b.Property<string>("ArtworkTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("artwork_types");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreationYear")
                        .HasColumnType("integer")
                        .HasColumnName("creation_year");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<decimal>("DimensionH")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dimension_h");

                    b.Property<decimal>("DimensionL")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dimension_l");

                    b.Property<string>("DimensionUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dimension_unit");

                    b.Property<decimal>("DimensionW")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dimension_w");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MaterialIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("material_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WeightCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("weight_category");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_artworks_is_deleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_artworks_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_artworks_status");

                    b.ToTable("artworks", "artwork_context");
                });
#pragma warning restore 612, 618
        }
    }
}
