name: CI/CD Workflow lajemacarts

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci


      - name: Lint
        run: npx nx affected -t lint

      - name: Test
        run: npx nx affected -t test

      - name: Build
        run: npx nx affected -t=build lajemacarts --production

  deploy:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NX CLI
        run: npm install -g nx

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Update federation manifest for production
        run: |
          sed -i 's|http://localhost:4201/remoteEntry.json|https://gallery.lajemacarts.fr/remoteEntry.json|g' apps/lajemacarts/public/federation.manifest.json

      - name: Determine affected projects
        id: affected
        run: |
          npx nx affected -t=build lajemacarts --production

      - name: Upload to o2switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/apps/lajemacarts/
          server-dir: /
